name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    # HTTP requests
  dio: ^5.4.0
  
  # Local database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.2
  
  # User preferences
  shared_preferences: ^2.2.2
  
  # QR code scanner
  mobile_scanner: ^3.5.5
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  
  # Calendar
  table_calendar: ^3.0.9
  
  # UI helpers
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
